eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}} # generate random instance id for each instance
spring:
  application:
    name: products-service
server:
  port: 0 # means random port on startup
